# Generated by Django 2.2.7 on 2019-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visited_places_app', '0003_place_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='comment',
            field=models.TextField(help_text='Прекрасное место для прогулки', verbose_name='Комментарий о месте'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Центральный парк', max_length=40, verbose_name='Название'),
        ),
    ]
