install: travis_wait mvn install
before_install:
  - sudo apt-get update
  - sudo apt-get install libproj-dev proj-data proj-bin
  - sudo apt-get install libgeos-dev
  - sudo apt-get install gdal-bin
  - sudo apt install postgis
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python mysite/manage.py test visited_places_app
  - coverage run --source=mysite/visited_places_app mysite/manage.py test visited_places_app
after_success: coveralls
