install: travis_wait mvn install
before_install:
  - sudo apt-get update
  - sudo apt-get install libproj-dev proj-data proj-bin
  - sudo apt-get install libgeos-dev
  - sudo apt install sqlite3
  - sudo apt-get install gdal-bin
  - sudo apt install libsqlite3-mod-spatialite

language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python mysite/manage.py test visited_places_app
  - coverage run --source=mysite/visited_places_app mysite/manage.py test visited_places_app
after_success: coveralls
