install: travis_wait mvn install
before_install:
  - sudo apt-get update
  - sudo apt-get install libproj-dev proj-data proj-bin
  - sudo apt-get install libgeos-dev
  - sudo apt-get install gdal-bin
services:
  - postgresql
addons:
  postgresql: "10.11"

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-10.11-postgis-2.4
  - psql -U postgres -c 'create database travis_ci_test'
  - psql -U postgres -d travis_ci_test -c 'create extension postgis'
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python mysite/manage.py test visited_places_app
  - coverage run --source=mysite/visited_places_app mysite/manage.py test visited_places_app
after_success: coveralls
