before_install:
  - sudo apt-get update
  - sudo apt-get install libproj-dev proj-data proj-bin
  - sudo apt-get install libgeos-dev
  - sudo apt install sqlite3
  - sudo apt install libsqlite3-mod-spatialite

language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python mysite/manage.py test visited_places_app
