# Generated by Django 2.2.7 on 2019-11-10 07:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('comment', models.TextField(verbose_name='Комментарий о месте')),
            ],
        ),
    ]
